import NavBar from '@/components/navigation/NavBar';
import SideBar from '@/components/navigation/SideBar';
import { Box, Toolbar } from '@mui/material';

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children, role, onLogout }) {
  return (
    <html>
      <body>
        <Box sx={{ display: 'flex' }}>
          <NavBar />
          <SideBar />
          <Box sx={{
            display: 'flex',
            flexDirection: 'column',
            width: 'calc(100% - 320px)',
            flexGrow: 1,
            height: '100vh',
          }}>
            <Toolbar />
            {children}
          </Box>
        </Box>
      </body>
    </html>
  );
}
